### PR TITLE
REP-34 Fix snackbar errors for deleting nodes

### LINKED ISSUE #34: Node deletion error does not disappear and cannot be dismissed
**Describe the bug**
When deleting a Node that is being used in a Replication, an error notification is presented but it cannot be dismissed.
The notifications also stack on each other.

**Affects version**
0.2.0

**To Reproduce**
1. Create a Node (2 if the local Node is not available)
2. Create a Replication between the 2 Nodes
3. Attempt to delete the node
4. An error notification should appear but it cannot be dismissed.

**Expected behavior**
The error message can be dismissed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Chrome

**Additional context**
Switching pages causes the notification to go away.

### PR DESCRIPTION
**Pull request by peterhuffer**
#### What does this PR do?
- Adds new component for snackbars when displaying node deletion errors.
- Snackbars dismiss within a certain time and no longer stack on each other. 
- Move tests to `__tests__` directories.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@kcover @clockard @mcalcote 

#### How should this be tested? (List steps with links to updated documentation)
- Create a node.
- Create a Replication between the local Node and the new Node.
- Try to delete a Node used in the Replication.
- Verify snackbars do not stack directly on each other, dismiss over time, and do not duplicate for the same error. 

Verify hovering over home and node icons on navigation menu show help text

#### What are the relevant tickets?
Fixes #34 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by peterhuffer** [comment]
build now

**Comment by clockard** [comment]
Manually tested and verified. ✅

**Comment by peterhuffer** [comment]
build now

**Comment by peterhuffer** [comment]
build now

**Comment by peterhuffer** [comment]
build now

**Pull request merged**
