### PR TITLE
Add priority

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Adds priority to replication jobs
Fixes a few small things as well

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@shaundmorris 
@sgalla 

Artificial delay was added for the video

https://user-images.githubusercontent.com/5248090/138153778-3600a904-584a-4284-8139-7ee5840cabdb.mp4

Update from what is shown in the video. Added ability to change priority from the table

Screen Shot 2021-10-20 at 5 32 21 PM

### CODE REVIEW

**Review by sgalla — APPROVED** [review]

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Review by sgalla — APPROVED** [review]

**Comment by clockard** [comment]
Build is failing because of existing owasp findings.

**Pull request merged**
