### PR TITLE
Update feature to not depend on admin-console feature repo.

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Also updated some imports to make replication work better across ddf versions

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@aaronilovici 

#### How should this be tested? (List steps with links to updated documentation)
Verify replication installs on ddf 2.26.3/alliance 1.15.1

### CODE REVIEW

**Review by figliold — APPROVED** [review]

**Review by jhunzik — APPROVED** [review]

**Review by aaronilovici — APPROVED** [review]

**Comment by clockard** [comment]
build now

**Comment by aaronilovici** [comment]
Tested this in Alliance 1.5.x, consider it heroed 👍

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Pull request merged**
