### PR TITLE
BR-42 Upgrade Maven version

### PR DESCRIPTION
**Pull request by TonyMorrison**
#### What does this PR do?
Upgrades the version of Maven in the pipeline from 3.5.x to maven-latest (Currently 3.6.3)

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@clockard 
@LinkMJB 

#### How should this be tested? (List steps with links to updated documentation)
Tested by running the pipeline here
http://jenkins.phx.connexta.com/job/W.I.P./job/Replication_TM/job/0.3.x/

#### What are the relevant tickets?
BR-42 Upgrade Maven version on Jenkins

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Review by clockard — APPROVED** [review]

**Comment by LinkMJB** [comment]
```
~ 🍺
matthew.bates@LinkMJB $ validate_jenkinsfile https://raw.githubusercontent.com/connexta/replication/c30a66e374b25ace678c6821b316e1452ae9b09d/Jenkinsfile
...Downloading Jenkinsfile
...Validating Jenkinsfile
Jenkinsfile successfully validated.
```

**Comment by LinkMJB** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by LinkMJB** [comment]
Build is failing due to problems contacting the NIST NVD upstream. There are optimizations that have been made in other Connexta/Codice projects to make use of a local MariaDB instance that can act as a proxy/mirror of the NIST NVD. Discussed with @TonyMorrison and we're going to track the problem as a result of the findings here. No need to block this PR on that work.

**Review by LinkMJB — APPROVED** [review]

**Pull request merged**
