### PR TITLE
Updating 0.3.x to have important commits from master

### PR DESCRIPTION
**Pull request by aaronilovici**
#### What does this PR do?
This adds to 0.3.x REP-119, REP-139, REP-142, enforcing of headers on Java files, some version upgrades, and updating the ddfNodeAdapter/Factory and its tests, and the ddfRestClient/Factory and its tests.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@cjlange
@clockard
@josephthweatt
@mdang8

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Review by josephthweatt — APPROVED** [review]

**Comment by aaronilovici** [comment]
build now

**Review by cjlange — APPROVED** [review]

**Review by clockard — APPROVED** [review]

**Comment by aaronilovici** [comment]
build now

**Review by mdang8 — APPROVED** [review]

**Comment by aaronilovici** [comment]
build now

**Comment by aaronilovici** [comment]
build now

**Pull request merged**
