### PR TITLE
certificate support

### PR DESCRIPTION
**Pull request by cjlange**
#### What does this PR do?
Adds support for use of certificates in an https scenario

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@aaronilovici 
@mdang8 
@josephthweatt 

#### How should this be tested? (List steps with links to updated documentation)

1. Follow the certificate setup instructions found here: https://confluence.di2e.net/display/I2O/CDF+WebHDFS+Replication+Notes
2. Build this branch
3. Startup a DIB on your local machine
4. Install the 0.3.0 replication kar file generated from this branch
5. Setup a one-way replication with DIB as the source and CDF as the destination.  The values for hostname, port, and root context for CDF will be provided upon request.
6. Ingest a file into your DIB
7. Confirm that the file is replicated to CDF after the replication period has elapsed by using cURL to list the contents in the remote directory

#### What are the relevant tickets?
[DIB-9618](https://jira.di2e.net/browse/DIB-9618)

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by cjlange** [comment]
build now

**Review by josephthweatt — APPROVED** [review]

**Review by aaronilovici — APPROVED** [review]
This looks good to me.

**Review by mdang8 — APPROVED** [review]

**Review by mdang8 — APPROVED** [review]

**Comment by mdang8** [comment]
✅ Hero success! I was able to verify that files were replicated to both a local HDFS instance and a remote instance. For the local instance, I set it up to be accessible over HTTP and HTTPS with self-signed certs. For the remote instance, I imported the server's certs to the DDF keystore/truststore and was able to connect to it with HTTPS.

**Comment by cjlange** [comment]
build now

**Comment by cjlange** [comment]
build now

**Review by aaronilovici — APPROVED** [review]

**Comment by cjlange** [comment]
build now

**Review by josephthweatt — APPROVED** [review]

**Pull request merged**
